M48
; DRILL file {KiCad 8.0.2} date 2025-03-10T15:18:08+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-10T15:18:08+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X194.395Y-64.11
X194.395Y-69.89
T2
X105.0Y-55.0
X105.0Y-145.0
X195.0Y-55.0
X195.0Y-145.0
M30
